version: '3.4'
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Fusion.0.to.1"
      ACCEPT_EULA: "Y"
    ports:
     - "127.0.0.1:5020:1433"
  tutorial:
    build: 
      context: .
      target: tutorial
    ports:
     - "50005:50005"
  sample_hello_world:
    build: 
      context: .
      target: sample_hello_world
  sample_hello_blazor_server:
    build: 
      context: .
      target: sample_hello_blazor_server
    ports:
     - "5000:5000"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5000"
      ASPNETCORE_ENVIRONMENT: "Development"
  sample_blazor:
    build: 
      context: .
      target: sample_blazor
    ports:
     - "5005:5005"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5005"
      ASPNETCORE_ENVIRONMENT: "Development"
