version: '3.4'
services:
  tutorial:
    build: 
      context: .
      target: tutorial
    ports:
     - "50005:50005"
  sample_hello_world:
    build: 
      context: .
      target: sample_hello_world
  sample_blazor:
    build: 
      context: .
      target: sample_blazor
    ports:
     - "5005:5005"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5005"
      ASPNETCORE_ENVIRONMENT: "Development"
