global using System;
global using System.Collections;
global using System.Collections.Immutable;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reactive;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Threading.Channels;
global using ActualLab;
global using ActualLab.Async;
global using ActualLab.Benchmarking;
global using ActualLab.Collections;
global using ActualLab.Reflection;
global using ActualLab.Serialization;
global using ActualLab.Text;
global using ActualLab.Time;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Logging.Abstractions;

global using static System.Console;
global using static Samples.RpcBenchmark.Program;
